# Source: rook-ceph-operator/templates/clusterrolebinding.yaml
# Grant the rook system daemons cluster-wide access to manage the Rook CRDs, PVCs, and storage classes
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rook-ceph-global
  labels:
    operator: rook
    storage-backend: ceph
    chart: "rook-ceph-operator-2.0.0"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rook-ceph-global
subjects:
- kind: ServiceAccount
  name: rook-ceph-system
  namespace: rook-ceph
- kind: ServiceAccount
  name: rook-ceph-system
  namespace: rook-cephfs
---
# Source: rook-ceph-operator/templates/clusterrolebinding.yaml
# Allow the ceph mgr to access cluster-wide resources necessary for the mgr modules
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rook-ceph-mgr-cluster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rook-ceph-mgr-cluster
subjects:
- kind: ServiceAccount
  name: rook-ceph-mgr
  namespace: rook-ceph
- kind: ServiceAccount
  name: rook-ceph-mgr
  namespace: rook-cephfs
---
# Source: rook-ceph-operator/templates/clusterrolebinding.yaml
# Allow the ceph osd to access cluster-wide resources necessary for determining their topology location
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rook-ceph-osd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rook-ceph-osd
subjects:
- kind: ServiceAccount
  name: rook-ceph-osd
  namespace: rook-ceph
- kind: ServiceAccount
  name: rook-ceph-osd
  namespace: rook-cephfs
---
# Source: rook-ceph-operator/templates/clusterrolebinding.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rook-ceph-object-bucket
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rook-ceph-object-bucket
subjects:
- kind: ServiceAccount
  name: rook-ceph-system
  namespace: rook-ceph
- kind: ServiceAccount
  name: rook-ceph-system
  namespace: rook-cephfs
---
# Source: rook-ceph-operator/templates/clusterrolebinding.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cephfs-csi-nodeplugin
roleRef:
  kind: ClusterRole
  name: cephfs-csi-nodeplugin
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: rook-csi-cephfs-plugin-sa
  namespace: rook-ceph
- kind: ServiceAccount
  name: rook-csi-cephfs-plugin-sa
  namespace: rook-cephfs
---
# Source: rook-ceph-operator/templates/clusterrolebinding.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cephfs-csi-provisioner-role
roleRef:
  kind: ClusterRole
  name: cephfs-external-provisioner-runner
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: rook-csi-cephfs-provisioner-sa
  namespace: rook-ceph
- kind: ServiceAccount
  name: rook-csi-cephfs-provisioner-sa
  namespace: rook-cephfs
---
# Source: rook-ceph-operator/templates/clusterrolebinding.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rbd-csi-provisioner-role
roleRef:
  kind: ClusterRole
  name: rbd-external-provisioner-runner
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: rook-csi-rbd-provisioner-sa
  namespace: rook-ceph
- kind: ServiceAccount
  name: rook-csi-rbd-provisioner-sa
  namespace: rook-cephfs
---
# Source: rook-ceph-operator/templates/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rook-ceph-system-psp
  labels:
    operator: rook
    storage-backend: ceph
    chart: "rook-ceph-operator-2.0.0"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'psp:rook'
subjects:
- kind: ServiceAccount
  name: rook-ceph-system
  namespace: rook-ceph
- kind: ServiceAccount
  name: rook-ceph-system
  namespace: rook-cephfs
---
# Source: rook-ceph-operator/templates/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rook-ceph-system-psp-users
  labels:
    operator: rook
    storage-backend: ceph
    chart: "rook-ceph-operator-2.0.0"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rook-ceph-system-psp-user
subjects:
- kind: ServiceAccount
  name: rook-ceph-system
  namespace: rook-ceph
- kind: ServiceAccount
  name: rook-ceph-system
  namespace: rook-cephfs
---
# Source: rook-ceph-operator/templates/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rook-csi-cephfs-provisioner-sa-psp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'psp:rook'
subjects:
- kind: ServiceAccount
  name: rook-csi-cephfs-provisioner-sa
  namespace: rook-ceph
- kind: ServiceAccount
  name: rook-csi-cephfs-provisioner-sa
  namespace: rook-cephfs
---
# Source: rook-ceph-operator/templates/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rook-csi-cephfs-plugin-sa-psp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'psp:rook'
subjects:
- kind: ServiceAccount
  name: rook-csi-cephfs-plugin-sa
  namespace: rook-ceph
- kind: ServiceAccount
  name: rook-csi-cephfs-plugin-sa
  namespace: rook-cephfs
---
# Source: rook-ceph-operator/templates/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rook-csi-rbd-plugin-sa-psp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'psp:rook'
subjects:
- kind: ServiceAccount
  name: rook-csi-rbd-plugin-sa
  namespace: rook-ceph
- kind: ServiceAccount
  name: rook-csi-rbd-plugin-sa
  namespace: rook-cephfs
---
# Source: rook-ceph-operator/templates/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rook-csi-rbd-provisioner-sa-psp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'psp:rook'
subjects:
- kind: ServiceAccount
  name: rook-csi-rbd-provisioner-sa
  namespace: rook-ceph
- kind: ServiceAccount
  name: rook-csi-rbd-provisioner-sa
  namespace: rook-cephfs
---
# Source: rook-ceph-operator/templates/clusterrolebinding.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rbd-csi-nodeplugin
roleRef:
  kind: ClusterRole
  name: rbd-csi-nodeplugin
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: rook-csi-rbd-plugin-sa
  namespace: rook-ceph
- kind: ServiceAccount
  name: rook-csi-rbd-plugin-sa
  namespace: rook-cephfs
---
# Source: rook-ceph-operator/templates/clusterrolebinding.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rook-ceph-admission-controller-rolebinding
roleRef:
  kind: ClusterRole
  name: rook-ceph-admission-controller-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: rook-ceph-admission-controller
  apiGroup: ""
  namespace: rook-ceph
- kind: ServiceAccount
  name: rook-ceph-admission-controller
  apiGroup: ""
  namespace: rook-cephfs
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rook-ceph-admin
roleRef:
  apiGroup: ""
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: rook-ceph-system
  namespace: rook-ceph
- kind: ServiceAccount
  name: rook-ceph-system
  namespace: rook-cephfs